development:
  adapter: postgresql
  encoding: unicode
  database: time_midpoint_development
  pool: 5
  username: Lopez
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: time_midpoint_test
  pool: 5
  username: Lopez
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: time_midpoint_production
  pool: 5
  username: Lopez
  password:
